### PR TITLE
added dates and item reviews to schema and loaded into database new r…

### PR DESCRIPTION
**Pull request by rchutzz**
updated my database to have some more fields to go for stretch goals on my review component

### CODE REVIEW

**Comment by hirichardhai** [comment]
@indegow 
@superhsu 
@Frogz1 

Hi! could any of you look over my updates to my schema/ database seed file. thanks

**Review by redharp — APPROVED** [review]
cool man

**Comment by hirichardhai** [comment]
thanks @Frogz1

**Comment by hirichardhai** [comment]
@Frogz1 
thanks!

**Pull request merged**
