### PR TITLE
Feat/fix readme and reviews state

### PR DESCRIPTION
**Pull request by rchutzz**
had some typos. reviews component now dynamically renders the proper number of review component depending on number of reviews received from a get request to a uniqueproductId.

also, readme wasn't updated for some reason.

### CODE REVIEW

**Comment by hirichardhai** [comment]
hey @Frogz1  could you please look over this small fixes? thanks

**Review by redharp — COMMENTED** [review]
Does the Review component require state or can it be a stateless component with props being passed down from a parent component?

**Comment by hirichardhai** [comment]
@Frogz1 
Was planning on having stretch goals of having longer reviews partially hidden and then clicking the "more" button to show the rest of the review. also, I want to add some underlining whenever the mouse over happens to thumbnail, username, and potentially side picture descriptions.

as of now, it isn't necessary, but hopefully I can use the state!

**Comment by Frogz1** [comment]
Okay I see,  cool well you have the green light to merge to me

**Pull request merged**
